config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :comics, only: :index do
    post :favorite
    patch :favorite
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  def self.marvel_comics
    marvel.comics(orderBy: 'focDate')
  end

  def self.marvel
    @marvel ||= config_marvel
  end

  def self.config_marvel
    marvel = Marvel::Client.new
    marvel.configure do |config|
      config.api_key = ENV['MARVEL_PUBLIC_KEY']
      config.private_key = ENV['MARVEL_PRIVATE_KEY']
    end
    marvel
  end
end

app/models/comics.rb
class Comics < ApplicationRecord
  scope :favorites, -> { where(favorite: true) }

  def self.all_comics(character_names)
    (favorites + complementary_comics(character_names))[0..19]
  end

  def self.complementary_comics(character_names)
    marvel_comics(character_names, 20 + favorites.count).map do |m_comics|
      Comics.new(marvel_id: m_comics.id, thumbnail_path: m_comics.thumbnail.path, thumbnail_extension: m_comics.thumbnail.extension)
    end.reject { |c| favorites.pluck(:marvel_id).include?(c.marvel_id) }
  end

  def self.marvel_comics(character_names, limit=20)
    marvel.comics({ limit: limit, orderBy: 'focDate', characters: characters(character_names) }.reject { |_, v| v.to_s.empty? })
  end

  def self.characters(character_names)
    return unless character_names

    character_names.split(',').map do |name|
      marvel.characters(nameStartsWith: name.strip).pluck(:id)
    end.reject { |c| c.empty? }.join(',')
  end

  def self.marvel
    @marvel ||= config_marvel
  end

  def self.config_marvel
    marvel = Marvel::Client.new
    marvel.configure do |config|
      config.api_key = ENV['MARVEL_PUBLIC_KEY']
      config.private_key = ENV['MARVEL_PRIVATE_KEY']
    end
    marvel
  end

  def cover_image
    "#{thumbnail_path}/portrait_uncanny.#{thumbnail_extension}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @comics = Comics.all_comics(params[:query])
  end

  def favorite
    comics = Comics.find_or_create_by(marvel_id: params[:comics_id])
    comics.update(comics_params.merge(favorite: !comics.favorite))
  end

  def comics_params
    params.require(:comics).permit(:thumbnail_path, :thumbnail_extension)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/comics/index.html.erb
<% @comics.each do |comic| %>
  <div class="comics-cover">
    <%= form_with model: comic, url: comics_favorite_path(comic.marvel_id), data: { action: "ajax:success->comics#search" } do |form| %>
      <%= image_tag "heart_#{comic.favorite ? 'on' : 'off'}.png", class: 'favorite' %>
      <%= form.hidden_field :thumbnail_path %>
      <%= form.hidden_field :thumbnail_extension %>

      <%= form.submit '', type: :image, src: comic.cover_image %>
    <% end %>
  </div>
<% end %>

app/views/home/index.html.erb
<div data-controller="comics" data-comics-url-value="/comics.html">
  <div class="comics-search">
    <%= image_tag 'marvel_logo.png', class: 'logo' %>
    <input data-comics-target="query" type="text" value="">
    <button data-action="click->comics#search">Search</button>
  </div>
  <div data-comics-target="list" class="comics">
    loading...
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marvel Comics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>